version: '2'
services:
  web:
    build: .
    command: npm run server
    volumes:
      - .:/home/roman/Documents/lala/pmmm
      - /home/roman/Documents/lala/pmmm/node_modules
    ports:
      - "3000:3000"
